BiciSendas/Areas/Monitorizacion/Controllers/SensorController.cs
using BiciSendas.Areas.Monitorizacion.Models.Sensores;
using BiciSendas.BL;
using BiciSendas.DA;
using BiciSendas.DA.DA;
using BiciSendas.DA.Entities;
using BiciSendas.Views.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace BiciSendas.Areas.Monitorizacion.Controllers
{
    [Area("Monitorizacion")]
    public class SensorController : Controller
    {

        private readonly SensorBL SensorBL;
        private readonly EstadoSensorBL EstadoSensorBL;
        private readonly TipoSensorBL TipoSensorBL;
        private static List<Sensor> sensores = new();

        public SensorController(EstadoSensorBL estadoSensorBL, SensorBL sensorBL, TipoSensorBL tipoSensorBL)
        {
            this.EstadoSensorBL = estadoSensorBL;
            this.SensorBL = sensorBL;
            this.TipoSensorBL = tipoSensorBL;
        }

        public async Task<IActionResult> Index()
        {
            SensorIndexVM model = new();

            model.Estados = await ObtenerComboEstados();
            sensores = await SensorBL.ObtenerSensores();
            model.TipoSensores = await ObtenerComboTipoSensor();
            return View(model);
        }

        [HttpGet]
        public async Task<JsonResult> ObtenerSensor(int idSensor)
        {
            try
            {
                Sensor? sensor = await SensorBL.ObtenerPorId(idSensor);
                SensorVM? sensorVM = MapearSensorToVM(sensor);

                return Json(sensorVM);
            }
            catch (Exception ex)
            {
                return Json(ex);
            }
        }
        [HttpGet]
        public async Task<JsonResult> ObtenerFiltrado(SensorIndexVM model)
        {
            try
            {
                SensorFiltro filtro = MapearFiltro(model);
                List<Sensor> sensores = await SensorBL.ObtenerFiltrado(filtro);

                return Json(new { sensores });
            }
            catch (Exception ex)
            {
                return Json(ex);
            }
        }

        private static List<SensorGridVM>? MapearSensoresToGrid(List<Sensor> sensores)
        {
            List<SensorGridVM> model = new List<SensorGridVM>();

            sensores.ForEach(i =>
            {
                SensorGridVM sensor = new();
                sensor.Identificador = i.IdSensor;
                sensor.TipoSensor = i.TipoSensor?.Nombre;
                sensor.Poblacion = i.Poblacion;
                sensor.Direccion = i.Direccion;
                sensor.FechaModificacion = i.FechaModificacion;
                sensor.Estado = i.EstadoSensor?.Nombre;
                sensor.IdEstadoSensor = i.IdEstadoSensor;
                
                model.Add(sensor);
            });

            return model;
        }

        private async Task<List<SelectListItem>> ObtenerComboEstados()
        {
            List<SelectListItem> combo = new();
            var estados = await EstadoSensorBL.ObtenerEstados();

            combo.Add(new SelectListItem { Value = "-1", Text = "Todos" });

            estados.ForEach(e => combo.Add(new SelectListItem { Value = e.IdEstadoSensor.ToString(), Text = e.Nombre }));

            return combo.OrderBy(e => e.Value).ToList();
        }
        private async Task<List<SelectListItem>> ObtenerComboTipoSensor()
        {
            List<SelectListItem> combo = new();
            var estados = await TipoSensorBL.ObtenerTiposSensores();

            combo.Add(new SelectListItem { Value = "-1", Text = "Todos" });

            estados.ForEach(e => combo.Add(new SelectListItem { Value = e.IdTipoSensor.ToString(), Text = e.Nombre }));

            return combo.OrderBy(e => e.Value).ToList();
        }

        private static SensorFiltro MapearFiltro(SensorIndexVM model)
        {
            SensorFiltro filtro = new();
            filtro.IdTipoSensor = model.IdTipoSensor < 0 ? null : model.IdTipoSensor;
            filtro.IdEstado = model.IdEstadoSensor < 0 ? null : model.IdEstadoSensor;

            return filtro;
        }

        private static SensorVM MapearSensorToVM(Sensor? sensor)
        {
            SensorVM sensorVM = new();
            //sensorVM.TipoSensor = sensor?.TipoSensor?.Nombre;
            //sensorVM.Descripcion = sensor?.Descripcion;
            //sensorVM.Fecha = sensor?.FechaModificacion.ToString();

            return sensorVM;
        }

        [HttpGet]
        public async Task<PartialViewResult> CargarSensores(string filtroIndex)
        {
            if (!string.IsNullOrEmpty(filtroIndex))
            {
                SensorIndexVM filtroVM = JsonConvert.DeserializeObject<SensorIndexVM>(filtroIndex)!;
                SensorFiltro filtro = MapearFiltro(filtroVM);
                sensores = await SensorBL.ObtenerFiltrado(filtro);
            }

            List<SensorGridVM>? items = MapearSensoresToGrid(sensores);

            return PartialView("_GridSensores", items);
        }
    }
}

BiciSendas/Areas/Operaciones/Controllers/ActuadorController.cs
using BiciSendas.Areas.Operaciones.Models.Actuadores;
using BiciSendas.BL;
using BiciSendas.DA;
using BiciSendas.DA.DA;
using BiciSendas.DA.Entities;
using BiciSendas.Views.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace BiciSendas.Areas.Operaciones.Controllers
{
    [Area("Operaciones")]
    public class ActuadorController : Controller
    {
        private readonly ActuadorBL ActuadorBL;
        private static List<Actuador> actuadores = new();
        private readonly TipoActuadorBL TipoActuadorBL;
        public ActuadorController(TipoActuadorBL tipoActuadorBL, ActuadorBL actuadorBL)
        {
            this.TipoActuadorBL = tipoActuadorBL;
            this.ActuadorBL = actuadorBL;
        }

        public async Task<IActionResult> Index()
        {
            ActuadorIndexVM model = new();

            model.TipoActuadores = await ObtenerComboTipoActuador();
            actuadores = await ActuadorBL.ObtenerActuadores();

            return View(model);
        }

        [HttpGet]
        public async Task<JsonResult> ObtenerActuador(int idActuador)
        {
            try
            {
                Actuador? actuador = await ActuadorBL.ObtenerPorId(idActuador);
                ActuadorVM? actuadorVM = MapearActuadorToVM(actuador);

                return Json(actuadorVM);
            }
            catch (Exception ex)
            {
                return Json(ex);
            }
        }

        [HttpGet]
        public async Task<JsonResult> ObtenerFiltrado(ActuadorIndexVM model)
        {
            try
            {
                ActuadorFiltro filtro = MapearFiltro(model);
                List<Actuador> actuadores = await ActuadorBL.ObtenerFiltrado(filtro);

                return Json(new { actuadores });
            }
            catch (Exception ex)
            {
                return Json(ex);
            }
        }

        private static List<ActuadorGridVM>? MapearActuadoresToGrid(List<Actuador> actuadores)
        {
            List<ActuadorGridVM> model = new();

            actuadores.ForEach(i =>
            {
                ActuadorGridVM actuador = new();
                actuador.Identificador = i.IdActuador;
                actuador.Nombre = i.Nombre;
                actuador.TipoActuador = i.TipoActuador?.Nombre;
                actuador.FechaModificacion = i.FechaModificacion;
                
                model.Add(actuador);
            });

            return model;
        }

        private async Task<List<SelectListItem>> ObtenerComboTipoActuador()
        {
            List<SelectListItem> combo = new();
            var estados = await TipoActuadorBL.ObtenerTiposActuadores();

            combo.Add(new SelectListItem { Value = "-1", Text = "Todos" });

            if(estados.Any())
                estados.ForEach(ta => combo.Add(new SelectListItem { Value = ta.IdTipoActuador.ToString(), Text = ta.Nombre }));

            return combo.OrderBy(ta => ta.Value).ToList();
        }

        private static ActuadorFiltro MapearFiltro(ActuadorIndexVM model)
        {
            ActuadorFiltro filtro = new();
            filtro.IdTipoActuador = model.IdTipoActuador < 0 ? null : model.IdTipoActuador;

            return filtro;
        }

        private static ActuadorVM MapearActuadorToVM(Actuador? actuador)
        {
            ActuadorVM actuadorVM = new();
            actuadorVM.TipoActuador = actuador?.TipoActuador?.Nombre;
            actuadorVM.Descripcion = actuador?.Descripcion;
            
            return actuadorVM;
        }

        [HttpGet]
        public async Task<PartialViewResult> CargarActuadores(string filtroIndex)
        {
            if (!string.IsNullOrEmpty(filtroIndex))
            {
                ActuadorIndexVM filtroVM = JsonConvert.DeserializeObject<ActuadorIndexVM>(filtroIndex)!;
                ActuadorFiltro filtro = MapearFiltro(filtroVM);
                actuadores = await ActuadorBL.ObtenerFiltrado(filtro);
            }

            List<ActuadorGridVM>? items = MapearActuadoresToGrid(actuadores);

            return PartialView("_GridActuadores", items);
        }
    }
}

BiciSendas/Areas/Operaciones/Controllers/ElementoViaController.cs
using BiciSendas.Areas.Operaciones.Models.ElementosVias;
using BiciSendas.BL;
using BiciSendas.DA.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BiciSendas.Areas.Operaciones.Controllers
{
    [Area("Operaciones")]
    public class ElementoViaController: Controller
    {
        private readonly ElementoViaBL ElementoViaBL;

        public ElementoViaController(ElementoViaBL elementoViaBL)
        {
            ElementoViaBL = elementoViaBL;
        }

        // GET: ElementoViaController
        public IActionResult Index()
        {
            ElementoViaIndexVM model = new();

            return View(model);
        }

        [HttpGet]
        public async Task<PartialViewResult> CargarElementosVia()
        {
            List<ElementoVia> elementos = await ElementoViaBL.ObtenerElementosVia();
            List<ElementoViaGridVM>? items = MapearElementosViaToVM(elementos);

            return PartialView("_GridElementoVia", items);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Grabar(ElementoViaIndexVM model)
        {
            if (!ModelState.IsValid) 
                return Json(new { success = false});

            ElementoVia elementoVia = MapearElementoViaVMToEntity(model);

            List<string> errores = ElementoViaBL.Validar(elementoVia);

            if (errores.Any())
            {
                return Json(new { success = false, errors = errores });
            }

            await ElementoViaBL.Grabar(elementoVia);

            return Json(new { success = true });
        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(int idElementoVia)
        {
            try
            {
                await ElementoViaBL.Eliminar(idElementoVia);

                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return Json(ex);
            }
        }

        private static ElementoVia MapearElementoViaVMToEntity(ElementoViaIndexVM model)
        {
            ElementoVia elementoVia = new();
            elementoVia.Identificador = model.Identificador?.Replace("'", "´").Trim();
            elementoVia.Nombre = model.Nombre?.Replace("'","´").Trim();
            elementoVia.TipoElemento = model.Nombre?.Replace("'", "´").Trim();

            return elementoVia;
        }

        private List<ElementoViaGridVM>? MapearElementosViaToVM(List<ElementoVia> elementos)
        {
            List<ElementoViaGridVM> model = new();

            elementos.ForEach(e =>
            {
                ElementoViaGridVM elemento = new();
                elemento.Id = e.IdElementoVia;
                elemento.Nombre = e.Nombre!.ToUpper();

                model.Add(elemento);
            });

            return model;
        }
    }
}

BiciSendas/Areas/Operaciones/Controllers/FaqController.cs
using BiciSendas.Areas.Operaciones.Models.Faqs;
using BiciSendas.BL;
using BiciSendas.DA.Entities;
using Microsoft.AspNetCore.Mvc;

namespace BiciSendas.Areas.Operaciones.Controllers
{
    [Area("Operaciones")]
    public class FaqController : Controller
    {
        private readonly FaqBL FaqBL;

        public FaqController(FaqBL faqBL)
        {
            this.FaqBL = faqBL;
        }

        public IActionResult Index()
        {
            FaqIndexVM model = new();
            
            List<Faq> faqs = FaqBL.ObtenerFaqs().Result;
            
            model.Faqs = MapearFaqsToGrid(faqs);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> ObtenerFaq(int idFaq)
        {
            try
            {
                Faq? faq = await FaqBL.ObtenerPorId(idFaq);
                FaqVM faqVM = MapearFaqToVM(faq);

                return Json(faqVM);
            }
            catch (Exception ex)
            {
                return Json(ex);
            }
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Grabar(FaqVM model, bool actualizarPosicion)
        {
            try
            {
                if (!ModelState.IsValid)
                    return Json(new { success = false });

                Faq? faq = await MapearFaqVMToEntity(model);

                await FaqBL.Guardar(faq, actualizarPosicion);

                return Json(new {success=true});

            }
            catch(Exception ex)
            {
                return Json(new {success=false, message= ex });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(int idFaq)
        {
            try
            {
                await FaqBL.Eliminar(idFaq);

                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return Json(ex);
            }
        }

        [HttpGet]
        public IActionResult ComprobarPosicion(int idFaq, int posicion)
        {
            try
            {
                bool existe = FaqBL.ExistePosicion(idFaq, posicion);

                return Json(existe);
            }
            catch(Exception ex)
            {
                return Json(ex);
            }
        }

        private async Task<Faq> MapearFaqVMToEntity(FaqVM model)
        {
            Faq? faq = new();

            if (model.IdFaq != 0)
            {
                faq = await FaqBL.ObtenerPorId((int)model.IdFaq);
                faq!.FechaModificacion = DateTime.Now;
            }
            else
            {
                faq.FechaAlta = DateTime.Now;
            }

            faq.Pregunta = model.Titulo;
            faq.Respuesta = model.Descripcion;
            faq.Posicion = model.Posicion!;

            return faq;
        }

        private static FaqVM MapearFaqToVM(Faq? faq)
        {
            FaqVM faqVM = new();
            faqVM.IdFaq = faq!.IdFaq;
            faqVM.Titulo = faq.Pregunta;
            faqVM.Descripcion = faq.Respuesta;
            faqVM.Posicion = faq.Posicion;

            return faqVM;
        }

        private static List<FaqGridVM>? MapearFaqsToGrid(List<Faq> faqs)
        {
            List<FaqGridVM> model = new();

            faqs.ForEach(i =>
            {
                FaqGridVM faq = new();
                faq.Identificador = i.IdFaq;
                faq.Pregunta = i.Pregunta;
                faq.Respuesta = i.Respuesta;
                faq.FechaAlta = i.FechaAlta;
                faq.FechaModificacion = i.FechaModificacion;
                faq.Posicion = i.Posicion;
                
                model.Add(faq);
            });

            return model;
        }
    }
}

BiciSendas/Views/Shared/_Layout.cshtml
@using BiciSendas.Resources
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BiciSendas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BiciSendas.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css"/>
    <link rel="stylesheet" href="~/lib/leaflet/leaflet.css"/>
    <link rel="stylesheet" href="~/css/mvc-grid/mvc-grid.css">
    <link rel="stylesheet" href="~/css/sweetalert2.css"/>
    <link rel="stylesheet" href="~/lib/leaflet/leaflet.css" />
    <link rel="stylesheet" href="~/lib/toastr.js/toastr.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BiciSendas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            @GlobalStrings.Monitorizacion
                          </a>
                          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-area="Monitorizacion" asp-controller="Incidencia" asp-action="Index">Incidencias</a></li>
                            <li><a class="dropdown-item" asp-area="Monitorizacion" asp-controller="Sensor" asp-action="Index">Sensores</a></li>
                          </ul>
                        </li>

                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            @GlobalStrings.Operaciones
                          </a>
                          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-area="Operaciones" asp-controller="Actuador" asp-action="Index">Actuadores</a></li>
                            <li><a class="dropdown-item" asp-area="Operaciones" asp-controller="ElementoVia" asp-action="Index">Elemento vía</a></li>
                            <li><a class="dropdown-item" asp-area="Operaciones" asp-controller="Faq" asp-action="Index">FAQs</a></li>
                          </ul>
                        </li>
                        
                    </ul>
                </div>
                <div id="dropdownLanguage" class="dropdown me-5">
                      <a class="btn btn-outline-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                          <img src="../images/flag_esp.png" alt="Español" style="width:20px; height:20px"/> ESP
                      </a>

                      <ul id="language" class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" href="#"><img src="../images/flag_cat.png" alt="Catalán" style="width:20px; height:20px"/> CAT</a></li>
                        <li><a class="dropdown-item" href="#"><img src="../images/flag_esp.png" alt="Español" style="width:20px; height:20px"/> ESP</a></li>
                      </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BiciSendas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/limonte-sweetalert2/sweetalert2.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/leaflet/leaflet.js"></script>
    <script src="~/js/mvc-grid/mvc-grid.js"></script>
    <script>
           document.querySelectorAll(".mvc-grid").forEach(element => new MvcGrid(element));
    </script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>