BiciSendas/Areas/Monitorizacion/Models/Incidencias/IncidenciaGridVM.cs
using BiciSendas.Resources;
using System.ComponentModel.DataAnnotations;

namespace BiciSendas.Areas.Monitorizacion.Models.Incidencias
{
    [Serializable]
    public class IncidenciaGridVM
    {
        [Display(Name = nameof(IncidenciaStrings.Identificador), ResourceType = typeof(IncidenciaStrings))]
        public int Identificador { get; set; }

        [Display(Name = nameof(IncidenciaStrings.TipoIncidencia), ResourceType = typeof(IncidenciaStrings))]
        public string? TipoIncidencia { get; set; }

        [Display(Name = nameof(IncidenciaStrings.Poblacion), ResourceType = typeof(IncidenciaStrings))]
        public string? Poblacion { get; set; }

        [Display(Name = nameof(IncidenciaStrings.Direccion), ResourceType = typeof(IncidenciaStrings))]
        public string? Direccion { get; set; }

        [Display(Name = nameof(IncidenciaStrings.FechaIncidencia), ResourceType = typeof(IncidenciaStrings))]
        public DateTime? FechaIncidencia { get; set; }

        [Display(Name = nameof(IncidenciaStrings.Estado), ResourceType = typeof(IncidenciaStrings))]
        public string? Estado { get; set; }

        public int IdEstado { get; set; }
    }
}

BiciSendas/Areas/Monitorizacion/Models/Incidencias/IncidenciaIndexVM.cs
using BiciSendas.Resources;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;


namespace BiciSendas.Areas.Monitorizacion.Models.Incidencias
{
    [Serializable]
    public class IncidenciaIndexVM
    {
        [Display(Name = nameof(IncidenciaStrings.FechaDesdeFiltro), ResourceType = typeof(IncidenciaStrings))]
        public DateTime? FechaDesde { get; set; }

        [Display(Name = nameof(IncidenciaStrings.FechaHastaFiltro), ResourceType = typeof(IncidenciaStrings))]
        public DateTime? FechaHasta { get; set; }

        [Display(Name = nameof(IncidenciaStrings.EstadoFiltro), ResourceType = typeof(IncidenciaStrings))]
        public int? Estado { get; set; }
        
        [Display(Name = nameof(IncidenciaStrings.PoblacionFiltro), ResourceType = typeof(IncidenciaStrings))]
        public string? Poblacion { get; set; }

        public List<SelectListItem>? Estados { get; set; }
        public List<IncidenciaGridVM>? Incidencias { get; set; }
    }
}

BiciSendas/Areas/Monitorizacion/Models/Incidencias/IncidenciaVM.cs
namespace BiciSendas.Areas.Monitorizacion.Models.Incidencias
{
    [Serializable]
    public class IncidenciaVM
    {
        public string? TipoIncidencia { get; set; }
        public string? Fecha { get; set; }
        public string? Descripcion { get; set; }
        public string? Imagen { get; set; }
    }
}

BiciSendas/Areas/Monitorizacion/Controllers/IncidenciaController.cs
using BiciSendas.Areas.Monitorizacion.Models.Incidencias;
using BiciSendas.BL;
using BiciSendas.DA;
using BiciSendas.DA.DA;
using BiciSendas.DA.Entities;
using BiciSendas.Views.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace BiciSendas.Areas.Monitorizacion.Controllers
{
    [Area("Monitorizacion")]
    public class IncidenciaController : Controller
    {
        private readonly IncidenciaBL IncidenciaBL;
        private readonly EstadoBL EstadoBL;
        private static List<Incidencia> incidencias = new();

        public IncidenciaController(EstadoBL estadoBL, IncidenciaBL incidenciaBL)
        {
            this.EstadoBL = estadoBL;
            this.IncidenciaBL = incidenciaBL;
        }

        public async Task<IActionResult> Index()
        {
            IncidenciaIndexVM model = new();
 
            model.Estados = await ObtenerComboEstados();
            incidencias = await IncidenciaBL.ObtenerIncidencias();

            return View(model);
        }

        [HttpGet]
        public async Task<JsonResult> ObtenerIncidencia(int idIncidencia)
        {
            try
            {
                Incidencia? incidencia = await IncidenciaBL.ObtenerPorId(idIncidencia);
                IncidenciaVM? incidenciaVM = MapearIncidenciaToVM(incidencia);

                return Json(incidenciaVM);
            }
            catch (Exception ex)
            {
                return Json(ex);
            }
        }

        [HttpGet]
        public async Task<JsonResult> ObtenerFiltrado(IncidenciaIndexVM model)
        {
            try
            {
                IncidenciaFiltro filtro = MapearFiltro(model);
                List<Incidencia> incidencias = await IncidenciaBL.ObtenerFiltrado(filtro);

                return Json(new { incidencias });
            }
            catch(Exception ex)
            {
                return Json(ex);
            }
        }

        private static List<IncidenciaGridVM>? MapearIncidenciasToGrid(List<Incidencia> incidencias)
        {
            List<IncidenciaGridVM> model = new List<IncidenciaGridVM>();

            incidencias.ForEach(i =>
            {
                IncidenciaGridVM incidencia = new();
                incidencia.Identificador = i.IdIncidencia;
                incidencia.TipoIncidencia = i.TipoIncidencia?.Nombre;
                incidencia.Poblacion = i.Poblacion;
                incidencia.Direccion = i.Direccion;
                incidencia.FechaIncidencia = i.Fecha;
                incidencia.Estado = i.Estado?.Descripcion;
                incidencia.IdEstado = i.IdEstado;

                model.Add(incidencia);
            });

            return model;
        }

        private async Task<List<SelectListItem>> ObtenerComboEstados()
        {
            List<SelectListItem> combo = new();
            var estados = await EstadoBL.ObtenerEstados();

            combo.Add(new SelectListItem { Value = "-1", Text = "Todos" });

            if(estados.Any())
                estados.ForEach(e => combo.Add(new SelectListItem { Value = e.IdEstado.ToString(), Text = e.Descripcion }));

            return combo.OrderBy(e=>e.Value).ToList();
        }

        private static IncidenciaFiltro MapearFiltro(IncidenciaIndexVM model)
        {
            IncidenciaFiltro filtro = new();
            filtro.Poblacion = model.Poblacion?.Replace("'","´");
            filtro.FechaDesde = model.FechaDesde;
            filtro.FechaHasta = model.FechaHasta;
            filtro.IdEstado = model.Estado < 0 ? null : model.Estado;

            return filtro;
        }

        private static IncidenciaVM MapearIncidenciaToVM(Incidencia? incidencia)
        {
            IncidenciaVM incidenciaVM = new();
            incidenciaVM.TipoIncidencia = incidencia?.TipoIncidencia?.Nombre;
            incidenciaVM.Descripcion = incidencia?.Descripcion;
            incidenciaVM.Fecha = incidencia?.Fecha.ToString();

            if (incidencia?.Foto != null)
            {
                var base64 = Convert.ToBase64String(incidencia.Foto);
                var Image = String.Format("data:image/gif;base64,{0}", base64);
                incidenciaVM.Imagen = Image;
            }
            return incidenciaVM;
        }

        [HttpGet]
        public async Task<PartialViewResult> CargarIncidencias(string filtroIndex)
        {    
            if (!string.IsNullOrEmpty(filtroIndex))
            {
                IncidenciaIndexVM filtroVM = JsonConvert.DeserializeObject<IncidenciaIndexVM>(filtroIndex)!;
                IncidenciaFiltro filtro = MapearFiltro(filtroVM);
                incidencias = await IncidenciaBL.ObtenerFiltrado(filtro);
            }

            List<IncidenciaGridVM>? items = MapearIncidenciasToGrid(incidencias);

            return PartialView("_GridIncidencias", items);
        }
    }
}

BiciSendas/Areas/Monitorizacion/Views/Incidencia/Index.cshtml
@using BiciSendas.Resources
@using NonFactors.Mvc.Grid
@model BiciSendas.Areas.Monitorizacion.Models.Incidencias.IncidenciaIndexVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .table-hover tbody tr:hover {
        background-color: rgba(0, 0, 0, 0.04);
    }
</style>

@section Scripts {
    <script src="~/js/incidencias.js"></script>
}   

@{
    ViewData["Title"] = "Incidencias";

    <div class="container d-flex flex-column">
        <div class="row">
            <div class="col-lg-2 ps-0">
                @Html.LabelFor(m => m.FechaDesde, null, new { @class="col-form-label"})
                @Html.TextBoxFor(model => model.FechaDesde, new { @type="date", @class = "form-control datepicker",  @Value = Model.FechaDesde?.ToString("dd/MM/yyyy") } )
            </div>
            <div class="col-lg-2">
                @Html.LabelFor(m => m.FechaHasta, null, new { @class="col-form-label"})
                @Html.TextBoxFor(model => model.FechaHasta, new { @type="date", @class = "form-control datepicker",  @Value = Model.FechaHasta?.ToString("dd/MM/yyyy") } )
            </div>
            <div class="col-lg-2">
                @Html.LabelFor(m => m.Estado, null, new {@class="col-form-label"})
                @Html.DropDownListFor(m => m.Estado, Model.Estados, new {@class="form-select"})
            </div>
            <div class="col-lg-3">
                @Html.LabelFor(m => m.Poblacion, null, new {@class="col-form-label"})
                @Html.EditorFor(m => m.Poblacion, new {htmlAttributes = new {@class="form-control"}})
            </div>
            <div class="col-lg-3 mt-auto ps-0">
                <button type="button" id="btnBuscar" class="btn btn-primary" onclick="filtrar()">Buscar</button>
                <button type="button" id="btnBorrar" class="btn btn-secondary" onclick="resetFiltro()">Borrar filtros</button>
            </div>
        </div>
    </div>

    <div id="ListaIncidencias" class="col-xs-12 mt-4">
        @Html.AjaxGrid(Url.Action("CargarIncidencias", "Incidencia", new { Area = "Monitorizacion" })!)
    </div>

    @* Modal detalle *@
    <div class="modal fade" id="modalIncidencia" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="title">
            </h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="col-lg-12">
                <image id="imagenIncidencia" style="height:250px; width: 100%;"></image>
            </div>
            <p id="fecha" class="col-lg-12" style="font-size:x-small"></p>
            <div id="descripcion" class="col-lg-12 mt-2">

            </div> 
          </div>
        </div>
      </div>
    </div>
}

BiciSendas/Areas/Monitorizacion/Views/Incidencia/_GridIncidencias.cshtml
@model List<BiciSendas.Areas.Monitorizacion.Models.Incidencias.IncidenciaGridVM>
@using NonFactors.Mvc.Grid

@{
    @(Html
            .Grid(Model)
            .Id("gridIncidencias")
            .Build(columns =>
            {
                columns.Add(model => model.Identificador);
                columns.Add(model => model.TipoIncidencia);
                columns.Add(model => model.Poblacion);
                columns.Add(model => model.Direccion);
                columns.Add(model => model.FechaIncidencia).Formatted("{0:d}");
                columns.Add(model => model.Estado).RenderedAs(model => "<span style='" + (model.IdEstado == 1 ? "color: green" : (model.IdEstado == 2 ? "color:orange" : "color:red")) + "'>" + model.Estado + "</span>").Encoded(false);
                columns.Add(model => "<button class='btnVer btn btn-secondary btn-sm fa-solid fa-magnifying-glass' data-id=\"" + model.Identificador + "\">").Encoded(false).Css("text-center").AsAttributes();
            })
            .Empty("No data found")
            .Pageable(pager =>
            {
                pager.PageSizes = new Dictionary<Int32, String> { { 0, "Todo" }, { 5, "5" }, { 10, "10" }, {20, "20"} };
                pager.ShowPageSizes = true;
                pager.PagesToDisplay = 5;
                pager.CurrentPage = 1;
                pager.RowsPerPage = 5;
            })
            .Sortable()
            .Css("css-classes") // Overwrites all classes with the new ones
            .AppendCss("table-hover") // Appends classes to the current ones
        )
}